### ISSUE TITLE
Use Green scope Documentation

### ISSUE THREAD

**Issue by prasunakaveti** [seb-oss/green#1046]
### Description

We found CSS leaks issues while on-boarding our MFE to public web in the test environments. Finally, we resolved the issue by addding the use-green scope in the green.scss

/* Custom import of green */
#your-app-content.use-green {
    @import "@sebgroup/chlorophyll/scss"; /* if you want all of green */
}
/* @use '@sebgroup/chlorophyll/scss/components/button'; */ 

It would be nice if the Green design library could update the use-green scope documentation for more usability

**Comment by vsjolander** [comment]
Hello Prasuna! Thanks for creating an issue.

We have [some documentation on this ](https://sebgroup.github.io/green/latest/chlorophyll/?path=/docs/use-cases-use-green-for-mfe-in-shell-application--page) but would you say it's too hard to find?
