### ISSUE TITLE
Stepper: button becomes white when hovered or pressed

### ISSUE THREAD

**Issue by vsjolander** [seb-oss/green#1100]
<img width="291" alt="Screenshot 2023-11-06 at 13 37 26" src="https://github.com/sebgroup/green/assets/11420341/80acb477-196d-4822-99bb-f4e76082e7da">

**Comment by EldRoos** [comment]
Hover is fixed but press and drag makes it white still.

**Comment by EldRoos** [comment]
Good enough!
