### ISSUE TITLE
CloseButton: No hover effect

### ISSUE THREAD

**Issue by EldRoos** [seb-oss/green#1139]
### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### Component name

CloseButton

### Description

Hover on the Close Button (x) will not show anything different (except changing the cursor).
Check Figma for more info.
Might be connected to this issue: #949

### Current Behaviour

Nothing visual is changed (except cursor).

### Expected Behaviour

Should change from transparent background to light grey circle when hovering.

**Comment by splashdust** [comment]
@EldRoos I am not able to reproduce this issue in Storybook, but it is possible that there are local variations of this component embedded in other components. Can you provide a link to where this problem occurs?

**Comment by krishi-agrawal** [comment]
I would like to work on this issue, can you assign it to me?

**Comment by EldRoos** [comment]
Fixed
