### ISSUE TITLE
Button: Grouped ghost buttons unreadable on tab + hover and click + drag actions

### ISSUE THREAD

**Issue by tobiaslundborg** [seb-oss/green#1177]
### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### Component name

Button

### Description

Grouped buttons get identical text and background colors which make the button unreadable in two use cases (see attached video):

#1: Tabbing to a button and then hovering on it
#2: Clicking, holding down and moving the cursor out of the button
![Grouped buttons rendered unreadable to the user in two different cases ](https://github.com/sebgroup/green/assets/148191557/30f0a58e-bf35-4f59-bdc5-b08896bf1bf5)

https://sebgroup.github.io/green/latest/chlorophyll/?path=/docs/components-form-elements-button--button

### Steps To Reproduce

#1: Tabbing to a button and then hovering on it
#2: Clicking, holding down and moving the cursor out of the button

**Comment by EldRoos** [comment]
I confirm this is still the case. Also found that if you hover and focus at same time it goes all black.
