### ISSUE TITLE
Datepicker: Paste format conversion

### ISSUE THREAD

**Issue by splashdust** [seb-oss/green#1231]
Currently, the Datepicker only runs pasted strings through the javascript `Date()` constructor. This can be a problem if the format of the Datepicker is set to something non-standard. That can cause dates copied from a Datepicker to not be pastable in an other instance of the component, for example.

The Datepicker should therefore support parsing that matching the configured formatting of the component. For example, if the `dateformat` attribute is set to `d/m/y`, a pasted string like `05/03/2024` should be properly parsed as `2024-03-05`

Additionally, it could be useful to support a callback function so that support for custom formats can be added on the consuming side.

**Comment by arekon7** [comment]
Hello, 
date pasting in other formats than Swedish now works buggy: when pasting in  formats `DD/MM/YYY` or  `DD.MM.YYY` : `DD `and `MM ` values getting mixed up. 

Steps to reproduce:
Go to https://storybook.seb.io/latest/angular/?path=/docs/components-datepicker--documentation#datepickeroptions page
Open date picker "Birthday"
Write value into DP: "07/03/2024"
Copy DP value
Paste it into DP again

Result:
Day and Month values mixed up.

Check attached video gif.

![DP-issue-copy-paste](https://github.com/seb-oss/green/assets/40074601/79c9698d-e7c9-4630-8ee9-0aaad57d36ed)
