### ISSUE TITLE
Datepicker: calendar modal changing height depending on month

### ISSUE THREAD

**Issue by arekon7** [seb-oss/green#1441]
### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

Angular

### Component name

Datepicker

### Description

Datepicker calendar modal changing height depending on month when navigating with Next/Previous arrows buttons. This causing inconvenience for smaller size screens, since it's jumping from top to bottom making it difficult and annoying to navigate through months using arrows.

Please check videos:

[DP-modal_changing-height.webm](https://github.com/seb-oss/green/assets/40074601/373b41d5-6aa3-4c6f-bc2e-4718bc3bda28)

DP used in AWC MFE:
https://sebgroup-my.sharepoint.com/:v:/g/personal/konstantinas_arefjevas_seb_se/EQClcqyhQ55BtadyB8yeBwUBh6arGlrEDQav2gZpCWc0Tw?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D&e=QcJKNo

### Steps To Reproduce

Steps to reproduce were written on 2024-06-14:

1. Go to https://storybook.seb.io/latest/angular/?path=/docs/components-datepicker--documentation#datepickeroptions page
2. Open datepicker "Birthday"
3. Using "Next" or "Previous" arrow navigate through months

### Current Behaviour

Datepicker calendar modal changing height causing modal to jump

### Expected Behaviour

Datepicker calendar modal have a static height making it more stable.

**Comment by EldRoos** [comment]
Ok yes that is irritating behavior when it all the sudden folds up instead of down because the height was not enough underneath. I wonder if an empty row would be the best thing to have on months having less weeks.
