### ISSUE TITLE
Datepicker: year loops around

### ISSUE THREAD

**Issue by arekon7** [seb-oss/green#1442]
### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

Angular

### Component name

Datepicker

### Description

Datepicker calendar "year" loops around. When navigating with "next" button till next year, it shows "1924" as a next year. 

Please check video:
[Dp-year-issue.webm](https://github.com/seb-oss/green/assets/40074601/fdbb74fd-720c-416c-99f2-505cfd6665f2)

### Steps To Reproduce

Steps to reproduce were written on 2024-06-14:

1. Go to https://storybook.seb.io/latest/angular/?path=/docs/components-datepicker--documentation#datepickeroptions page
2. Open datepicker "Birthday"
3. Using "Next" arrow navigate through months till the next year

### Current Behaviour

Next year is shown as 1924 (first option form the years list)

### Expected Behaviour

Disabled over looping to the first year option from list.

**Comment by EldRoos** [comment]
I can confirm. It's same on the "normal" datepicker **Date**. If you go over 2034 you go to 2014.
