### ISSUE TITLE
add aria label on the drop down component

### ISSUE THREAD

**Issue by SEBEric** [seb-oss/green#1480]
### Does the component already exist

- [X] I confirm that I have checked if the component already exists in any of the Green libraries

### For which framework/library you are requesting the component

Angular

### Description

add the possibility to set  aria label on the drop down component

### Who will benefit from this feature?

everyone

**Comment by splashdust** [comment]
You can set the label using the `label` input. This will set the accessible label for the component (using `aria-label` internally on the appropriate element). If you need to render the component without a visible label, you can set the `hideLabel` input to `true`.

**Comment by SEBEric** [comment]
These is not suppose to be a label in the app

**Comment by splashdust** [comment]
Yes, I understand. That is what the `hideLabel` input does.

Like this: https://storybook.seb.io/pr-1485/core/?path=/docs/docs-components-dropdown--docs#hidden-label

**Comment by SEBEric** [comment]
I see, thanks :)
