### ISSUE TITLE
Pagination: Size issue

### ISSUE THREAD

**Issue by SEBEric** [seb-oss/green#1481]
### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

Chlorophyll

### Description

if you remove the "small" class on the nav element the pagination component becomes smaller
<img width="955" alt="image" src="https://github.com/seb-oss/green/assets/105651567/69dbc731-862b-49bb-94db-7fa0aa8135f4">
because of this css:
<img width="359" alt="image" src="https://github.com/seb-oss/green/assets/105651567/b1064c22-261f-405c-bc75-2f912d1a9603">

**Comment by EldRoos** [comment]
Confirmed this strange behavior. Removing small makes the gaps shorter. Both sizes is still 16px. But if I check the design, there should be a 14px version too.

**Comment by EldRoos** [comment]
Ok there is a "large" version too. That one should be the default one - so if small or large is omitted it should still be large. Will check if all sizes are correct.

**Comment by EldRoos** [comment]
Correct sizes on both, except all but first button have a margin-top 4px, so they are not aligned.
