### ISSUE TITLE
Dropdown: Issues with closing the dialog in Firefox

### ISSUE THREAD

**Issue by SEBRedas** [seb-oss/green#1503]
### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

React

### Component name

dropdown

### Description

With Chrome or Edge it is possible to close dropdown by either clicking on the form or anywhere outside the dialog. Meanwhile in Firefox it's only closing when item is selected (single-selection) or only by pressing ESC button in case dropdown is multi-select.
Such behavior can be seen in the Storybook itself.

### Steps To Reproduce

1. Visit [Storybook React/Dropdown - multi-select](https://storybook.seb.io/latest/react/?path=/docs/components-dropdown--docs#multi-select)
2. Click on  dropdown where multi-select is enabled
3. Try clicking anywhere around the dropdown - it is not possible to close it after selecting anything. Only ESC will close the dialog.

### Expected Behaviour

Dropdown should behave in Firefox the same way it does in any other supported browser.

**Comment by EldRoos** [comment]
Confirmed. I get same bug!
