### ISSUE TITLE
Datepicker: Calendar icon is bigger in Edge browser

### ISSUE THREAD

**Issue by SEBRedas** [seb-oss/green#1504]
### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

React

### Component name

datepicker

### Description

Calendar icon in Datepicker component differs in size when using Edge browser when compared to others.
Firefox: ![image](https://github.com/user-attachments/assets/f054134c-acf7-408d-a180-bdd36eb2eff1)
Edge: ![image](https://github.com/user-attachments/assets/e10399cb-ce56-4acd-9ac5-992742ffe489)

### Steps To Reproduce

1. Visit [Storybook React/Datepicker](https://storybook.seb.io/latest/react/?path=/docs/components-datepicker--docs) with Edge and Chrome for example.
2. Notice calendar icon size differences between two browsers.

### Expected Behaviour

Component and it's parts (icon) are looking the same in any supported browser.

**Comment by EldRoos** [comment]
They look the same size for me if I check Storybook. Here is a screenshot for Edge/Firefox/Chrome.
![Icons](https://github.com/user-attachments/assets/9d7670c7-0714-4212-b09a-df67d4b5baad)

Is the error in your application or when you view the storybook?
https://storybook.seb.io/latest/react/?path=/docs/components-datepicker--docs

**Comment by SEBRedas** [comment]
Seems that the issue was fixed in newer versions without directly addressing this issue. Closing this.
