### ISSUE TITLE
Typography: some sizes are not working properly

### ISSUE THREAD

**Issue by vsjolander** [seb-oss/green#1531]
Looks like some sizes are not working properly in the `gds-text` component. See it [here in the storybook](https://storybook.seb.io/latest/core/?path=/docs/docs-content-text--docs#title).

It's probably tokens values that are not set up properly.

**Comment by astrit** [comment]
Sync the `https://www.figma.com/design/xNUB1flVvMJUTXnbZxvgKW/Typography` to tokens repo and variables file. 

TODO:
1. Sync all sizes to tokens 
2. Update the storybooks with the new sizes 
3. Announce the change
