### ISSUE TITLE
TypeError: tokesStyleSheets.replaceSync is not a function

### ISSUE THREAD

**Issue by PierreSEBank** [seb-oss/green#1582]
### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

Angular

### Description

I am getting this error when I try to run "jest --coverage --runInBand"

![image](https://github.com/user-attachments/assets/8ace77dc-1dee-44bb-8672-6cb73f6d0959)

### Current Behaviour

TypeError: tokesStyleSheets.replaceSync is not a function

### Expected Behaviour

No error

**Comment by splashdust** [comment]
Using the Jest config from Green should solve this issue: https://storybook.seb.io/latest/angular/?path=/docs/testing--docs

Feel free to reopen this if it doesn't work!
