### ISSUE TITLE
Modal: Unit tests failing

### ISSUE THREAD

**Issue by karolis-leonas** [seb-oss/green#1601]
Angular application unit tests (Jest) with NggModal import seem to be failing to run now

### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

Angular

### Component name

modal

### Description

Hello, not sure if unit testing issues with Green imports should be communicated as an issue, but I'm trying my luck here now since I feel stuck at the moment :)
So, after trying out updating Green versions to newer ones, we noticed that some of our unit tests which reference NggModalModule import seem to be failing to run now, even though they did work before without code changes.

Testing framework throws an error:

"Test suite failed to run
TypeError: tokesStyleSheets.replaceSync is not a function"

This issue happens with:
- Green Angular version 3.8.0
- Chlorophyll 3.6.2 and 3.6.3
- Green Core versions 1.41.3 and 1.41.4
While our application uses Jest version 29.7.0

Do you know if there are any recent or important changes for NggModalModule which could have caused this kind of error to be thrown, or if you know by any change on how can we mitigate it?

If you have more questions - please contact me.

Huge thanks in advance!

### Current Behaviour

Currently our failing Jest unit tests throw this kind of response:
![image](https://github.com/user-attachments/assets/7307a570-1804-419a-8e51-01d571f096c0)

### Expected Behaviour

Test suite should start running properly as it did before.

**Comment by splashdust** [comment]
You need to mock some browser APIs ro run Green Core in Jest. Here's a guide: https://storybook.seb.io/latest/angular/?path=/docs/testing--docs

Also, when you import the component, you should import it from the sub path:
```ts
import { NggModalModule } from '@sebgroup/green-angular/src/lib/modal'
```

Otherwise you end up importing the entire library, which includes web components you may not be using. Since those are automatically registered with the browser (ie, side-effects), the compiler cannot tree-shake them.

**Comment by karolis-leonas** [comment]
Thanks a lot, your suggestion and linking to the support docs solved our issue! Closing this ticket now.
