### ISSUE TITLE
Datepicker: Label line-height does not match other inputs

### ISSUE THREAD

**Issue by gabrieledaugenaite** [seb-oss/green#1609]
### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

Angular

### Component name

datepicker

### Description

There seems to be inconsistencies between `line-height` for `label` in `datepicker` component and other input components (dropdown, label + native HTML input).

For `dropdown` it seems to be set to `1.25rem` in [transitional styles](https://github.com/seb-oss/green/blob/fbecda4116fe4ca5e3fa16ceee48b8515d211195/libs/core/src/components/dropdown/dropdown.trans.styles.scss#L103)

For `label` elements that we use next to native HTML input it also seems to be set to `1.25rem` in [form mixins](https://github.com/seb-oss/green/blob/fbecda4116fe4ca5e3fa16ceee48b8515d211195/libs/chlorophyll/scss/components/form/common/_mixins.scss#L243)

However, `datepicker` `label` does not have any `line-height` set in [transitional styles](https://github.com/seb-oss/green/blob/fbecda4116fe4ca5e3fa16ceee48b8515d211195/libs/core/src/components/datepicker/datepicker.trans.styles.scss#L13) and therefore `line-height` from [_body-default mixin](https://github.com/seb-oss/green/blob/fbecda4116fe4ca5e3fa16ceee48b8515d211195/libs/chlorophyll/scss/components/reset/mixins.scss#L51) is being used, which is only `1.125rem`

![{215D6126-DDEF-4128-B064-45A95E00E52F}](https://github.com/user-attachments/assets/7289c5e9-7656-4d66-8a08-e7ad3dba52d6)

**Comment by EldRoos** [comment]
@gabrieledaugenaite looks like it is fixed now right?

**Comment by gabrieledaugenaite** [comment]
@EldRoos no, doesn't look like it is fixed. I tried `@sebgroup/green-angular v5.0.0`, but still seems that `gds-datepicker` label is missing line-height :) 

Datepicker trans styles file [here](https://github.com/seb-oss/green/blob/%40sebgroup/green-angular%405.0.0/libs/core/src/components/datepicker/datepicker.trans.styles.scss#L13)
