### ISSUE TITLE
Modal: Unable scroll in Modals in iOS

### ISSUE THREAD

**Issue by prasunakaveti** [seb-oss/green#1742]
Unable to scroll down for the dropdown list inside Modal in ios devices

### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

React

### Component name

Modal

### Description

Tested in iOS platform. When the modal's body content is quite long and the modal scroll is not working.

### Steps To Reproduce

1. Prepare a modal, with long list items or use a dropdown with long list items.
2. Open the dropdown or modal 
3. Now, you can see the modal body is not scrollable.

### Current Behaviour

The modal body is not scrollable when having long list items in ios devices.

### Expected Behaviour

The modal body should be  scrollable when having long list items in ios devices.

**Comment by splashdust** [comment]
@prasunakaveti A solution is on the way in #1772

The Modal component now has a `enableBodyScrollLock` prop that you can use to disable the locking behavior. You can use that to disable bodyScrollLock when the dropdown opens.

Something like this:

```jsx
const [enableScrollLock, setEnableScrollLock] = useState(true)

...

<Modal
  enableBodyScrollLock={enableScrollLock}
>
  <Dropdown onGdsUiState={(e: CustomEvent) => setEnableScrollLock(!e.detail.open)} />
</Modal>
```
Now the locking should be disabled while the Dropdown is open.

This is not an ideal solution, but a fully rewritten version of the modal component is in development and it will solve this and other current modal issues in more robust ways.
