### ISSUE TITLE
Pagination: Should listen to Space input

### ISSUE THREAD

**Issue by tobiaslundborg** [seb-oss/green#1785]
### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

Angular

### Component name

Pagination

### Description

Space (keyboard input) does not currently trigger page change on the pagination component. Focusing on an unselected page and pressing the space bar does not change the table page.

### Steps To Reproduce

In BA or Nexus, go to Global Custody -> Fund Execution -> Approve orders -> See pagination below the table.

### Current Behaviour

Space does not trigger age change

### Expected Behaviour

Space should trigger page change

**Comment by EldRoos** [comment]
I confirm this in Angular Storybook:
https://storybook.seb.io/latest/angular/?path=/story/components-navigation-pagination--default

But maybe they should behave like links and not buttons - links also ignore space?
