### ISSUE TITLE
Improve developer experience on Windows machine

### ISSUE THREAD

**Issue by vsjolander** [seb-oss/green#725]
It's not optimal right now.

Seems like we still rely on node-gyp witch is a pain to install on Windows machines since it needs SDKs and other dependancies making the installation process far to long.

This needs to be optimized....

**Comment by patrikfogelstrand** [comment]
I think it's really important to differentiate between dev experience on a SEB Windows machine and any Windows machine. 

For any Windows:
- node-gyp is a (sub)dependency of the repo, which needs both [Python and a Windows SDK](https://github.com/nodejs/node-gyp#on-windows) installed. This is just a real pain, as a developer for a Node based application, I would prefer not having to install Python, Windows SDK, Visual Studio (full fledged), C++ tools, etc. 

Additional stuff for SEB Windows:
- different git configs needed for on-prem vs. cloud github ([solution](https://stackoverflow.com/a/43884702/12416767) but requires a lot of config and understanding of SEB networking)
- yarn seems pretty much impossible to use, atleast without any major config

**Comment by splashdust** [comment]
Many improvements and upgrades have been made since this issue was opened. It's still far from ideal, but this issue is very open ended, so I'm closing it now, and new and more specific issues can be opened as needed.
