### ISSUE TITLE
Workflow builds packages twice with ngx-deploy-npm

### ISSUE THREAD

**Issue by vsjolander** [seb-oss/green#727]
When building with NX and executors there was a problem when building and publishing with only `ngx-deploy-npm`. The problem seems to be how libs/packages resolves. When building with `ngx-deploy-npm` typescript fails on resolving `extract`.

Adding a build step before fixes this because the buildstep seems to resolve and cache `extract`some how 🤔 

Have to look further into this...

**Comment by splashdust** [comment]
I think this shouldn't be a problem anymore since we migrated publishing to Changesets
